### PR TITLE
Adding `slackId` to message spec

### PR DESCRIPTION
**Pull request by oliikit**
@k-mahoney is the display name still required now? Or can that be made optional/deleted?

### CODE REVIEW

**Comment by k-mahoney** [comment]
Slack `display_name` is now optional, correct.

**Comment by oliikit** [comment]
Okay, I just removed `slack` all in all from the message spec and cleaned up the references. I figured anyone using a Slack integration is aware of the change, so I didn't include the [Slack PSA](https://api.slack.com/changelog/2017-09-the-one-about-usernames) about it; maybe this is too much of a broad assumption to make.

**Comment by k-mahoney** [comment]
We should retain `slack: 'STRING_VALUE', // optional, Slack handle` - it is still used for human readable context in https://github.com/mapbox/dispatch/pull/116#issuecomment-364471094. We can review this closer to the Slack's deprecation in September.

**Comment by k-mahoney** [comment]
LGTM @oliikit

**Pull request merged**
